[package]
name = "get_launch_arg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
safe_drive = "0.2"

[package.metadata.ros]
safe_drive_version = "0.2"
